### ISSUE TITLE
Implement quickcheck::Arbitrary for ethereum-types

### ISSUE THREAD

**Issue by debris** [paritytech/primitives#21]
as mentioned in the comment https://github.com/paritytech/parity-bridge/pull/114#discussion_r168425202

**Comment by snd** [comment]
@debris you already implemented arbitrary for uints ; )
https://github.com/paritytech/primitives/blame/master/tests/src/uint_tests.rs#L1022

great!

i'll move it out of tests so it can be used from other crates.
also i'll add arbitrary for the hash types.

will feature gate it

**Comment by debris** [comment]
> @debris you already implemented arbitrary for uints ; )

I believe you did this. or andre ;)

**Comment by snd** [comment]
resolved in https://github.com/paritytech/primitives/pull/22
