### ISSUE TITLE
error: inline assembly is not stable enough for use and is subject to change

### ISSUE THREAD

**Issue by snd** [paritytech/primitives#6]
i'm trying to use the ethereum-types crate for benchmarks in paritydb so they don't have to depend on all of parity. specifically i need `H160`. (https://github.com/paritytech/paritydb/issues/45#issuecomment-346655071, https://github.com/paritytech/paritydb/issues/45#issuecomment-347159200)

i've added it to `Cargo.toml` like so:
```
ethereum-types = { git = "https://github.com/paritytech/primitives" }
```

```
$ rustc --version
rustc 1.23.0-nightly (827cb0d61 2017-11-26)
```

when i run `cargo bench` i get `error: Could not compile ethereum-types` with a lot of errors like:
```
error: inline assembly is not stable enough for use and is subject to change (see issue #29722)
 --> /Users/basilisk/.cargo/git/checkouts/primitives-d1f10887bbb6b363/d910e92/ethereum-types/src/uint.rs:2:1
  |                                                             
2 | construct_uint!(U256, 4);                                                                                               
  | ^^^^^^^^^^^^^^^^^^^^^^^^^             
  |                                                                                            
  = help: add #![feature(asm)] to the crate attributes to enable                                            
  = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)
                             
error: inline assembly is not stable enough for use and is subject to change (see issue #29722)
 --> /Users/basilisk/.cargo/git/checkouts/primitives-d1f10887bbb6b363/d910e92/ethereum-types/src/uint.rs:2:1
  |                                                             
2 | construct_uint!(U256, 4);                                                                                               
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
  |                                                                                            
  = help: add #![feature(asm)] to the crate attributes to enable                                            
  = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)
```

**Comment by snd** [comment]
cloning this repo, depending on the local version and adding `#![feature(asm)]` to https://github.com/paritytech/primitives/blob/master/ethereum-types/src/lib.rs has solved the issue for me. let me know if you want a PR with the change

**Comment by debris** [comment]
I believe that this feature was added in `build.rs` for rust nightly, but it somehow got lost during the refactor

**Comment by snd** [comment]
running into this here again:
https://travis-ci.org/paritytech/paritydb/jobs/309995441#L784

let me know how to fix this and i'll do a PR

**Comment by tomusdrw** [comment]
@snd have a look at this build script: https://github.com/paritytech/bigint/blob/master/build.rs#L15 We need exactly something like this. (unless there is a better way to add this attribute conditionally on nightly).
